name: Deploy-project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: GetCode
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3  
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run test 
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the GetCode
        uses: actions/checkout@v3
      - name: Installing nodejs
        uses: actions/setup-Node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build test-project
        run: npm run build
      - name: deploy
        run: echo "deployed"
        